<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2HixPI\Eccube_KernelInstallContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2HixPI/Eccube_KernelInstallContainer.php') {
    touch(__DIR__.'/ContainerC2HixPI.legacy');

    return;
}

if (!\class_exists(Eccube_KernelInstallContainer::class, false)) {
    \class_alias(\ContainerC2HixPI\Eccube_KernelInstallContainer::class, Eccube_KernelInstallContainer::class, false);
}

return new \ContainerC2HixPI\Eccube_KernelInstallContainer([
    'container.build_hash' => 'C2HixPI',
    'container.build_id' => '1fbee49a',
    'container.build_time' => 1740621856,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2HixPI');
