<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJesLzqq\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJesLzqq/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJesLzqq.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJesLzqq\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerJesLzqq\Eccube_KernelProdContainer([
    'container.build_hash' => 'JesLzqq',
    'container.build_id' => 'd5c00dc6',
    'container.build_time' => 1740969560,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJesLzqq');
